displayName: request mark
type: middleware
import: github.com/qxsugar/request-mark
summary: mark requests according to the rules

testData:
  request-mark:
    logLevel: DEBUG

    serviceName: api
    redisEnable: false
    redisAddr: redis-server
    redisPassword: ""
    redisRulesKey: "redis_rules_key"
    redisRuleMaxLen: 256
    redisLoadInterval: 15
    markKey: X-DISPATCH
    headerVersion: X-version
    headerIdentify: identify
    cookieIdentify: identify-cookie
    queryIdentify: identify-query
    rules:
      - serviceName: api
        name: name
        enable: true
        priority: 100
        type: path
        markValue: alpha
        maxVersion: 3.3.3
        minVersion: 2.2.2
        userIds:
          - A001
          - A002
        weight: 80
        path: alpha
